# Generated by Django 5.0.1 on 2024-01-31 20:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Дело', 'verbose_name_plural': 'Дела'},
        ),
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Как именно делать'),
            preserve_default=False,
        ),
    ]
